version: '3'
services:
  integration-incident:
    image: 'diwise/integration-incident:latest'
    build: 
        context: ..
        dockerfile: ./deployments/Dockerfile
    restart: always
    environment: 
      DIWISE_BASE_URL: $DIWISE_BASE_URL
      GATEWAY_URL: $GATEWAY_URL
      AUTH_CODE: $AUTH_CODE
      SERVICE_PORT: '8282'
    
    ports:
      - '8282'
