version: '3'
services:
  opendata:
    image: 'diwise/api-opendata:latest'
    build: 
        context: ..
        dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on: 
      - pointofinterest
      - rabbitmq
    links:
      - pointofinterest
      - rabbitmq
    environment: 
      DIWISE_BASE_URL: $DIWISE_BASE_URL
      GATEWAY_URL: $GATEWAY_URL
      AUTH_CODE: $AUTH_CODE
      API_KEY: $API_KEY
    
    ports:
      - '8282'
